USE [master]
GO

/****** Object:  Database [localdbpet]    Script Date: 17/11/2019 20:42:09 ******/
CREATE DATABASE [localdbpet]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'localdbpet', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\localdbpet.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'localdbpet_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\localdbpet_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [localdbpet].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [localdbpet] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [localdbpet] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [localdbpet] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [localdbpet] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [localdbpet] SET ARITHABORT OFF 
GO

ALTER DATABASE [localdbpet] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [localdbpet] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [localdbpet] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [localdbpet] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [localdbpet] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [localdbpet] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [localdbpet] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [localdbpet] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [localdbpet] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [localdbpet] SET  DISABLE_BROKER 
GO

ALTER DATABASE [localdbpet] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [localdbpet] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [localdbpet] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [localdbpet] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [localdbpet] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [localdbpet] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [localdbpet] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [localdbpet] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [localdbpet] SET  MULTI_USER 
GO

ALTER DATABASE [localdbpet] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [localdbpet] SET DB_CHAINING OFF 
GO

ALTER DATABASE [localdbpet] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [localdbpet] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [localdbpet] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [localdbpet] SET QUERY_STORE = OFF
GO

ALTER DATABASE [localdbpet] SET  READ_WRITE 
GO

